name = "plinth-site"
compatibility_date = "2026-09-01"
workers_dev = true

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[[routes]]
pattern = "plinthrun.com"
custom_domain = true

[[routes]]
pattern = "www.plinthrun.com"
custom_domain = true

[observability]
enabled = true
