/** Category-level depth appended to every guide in the category. */
export const CATEGORY_PAD: Record<"Forms" | "Catch" | "Schema" | "Platform", string> = {
  Forms: `
<h2>Forms on the plotting sheet</h2>
<p>Plinth <a href="/forms">Forms</a> is the bearing most static-site builders plot first: a single POST URL, spam screening, and a readable inbox. You do not provision a database, mail server, or serverless function for a contact page. The browser does what it has done since HTML was invented — submit a form — and Plinth does what SaaS form backends do in the cloud.</p>
<p>Every form integration in this category shares the same contract: <code class="inline-code">method="POST"</code>, <code class="inline-code">action</code> pointing at <code class="inline-code">https://api.plinthrun.com/v1/forms/…</code>, optional <code class="inline-code">_redirect</code>, and a honeypot field documented in <a href="/guides/honeypot-spam-form">honeypot spam form</a>. Framework guides differ only in where that HTML is authored — Astro components, Hugo partials, Eleventy shortcodes, or Next.js JSX.</p>
<p>When comparing vendors, read <a href="/guides/formspree-free-tier-limit">Formspree free tier limits</a> and <a href="/guides/netlify-forms-alternative">Netlify Forms alternative</a>. When comparing hosting strategies, remember the form action is portable: changing from Netlify to Cloudflare Pages is a one-line action URL swap, not a migration of server code.</p>
<p>Operational concerns: free tier retention is 24 hours — enough to verify integration, not enough for compliance archives. Plan <a href="/pricing">Forms Pro</a> before launch if you need webhooks to Slack, CRM, or your own <a href="/guides/nextjs-contact-form">Next.js</a> API. API keys (<a href="/docs/api-keys">docs</a>) attach after Polar checkout — <a href="/guides/polar-billing-api-keys">billing guide</a>.</p>
<p>Self-hosters embed <code class="inline-code">@plinth/forms</code> per <a href="/guides/open-core-form-backend">open-core form backend</a>. Whether hosted or self-hosted, keep field names stable and test from production origin after every deploy. Submissions are the source of truth for customer conversations — treat form changes with the same care as pricing page copy.</p>
<h2>Forms API quick reference</h2>
<p>Create authenticated: <code class="inline-code">POST /v1/forms</code> with <code class="inline-code">x-plinth-key</code>. Anonymous: <code class="inline-code">POST /v1/forms/anonymous</code>. Submit: POST to <code class="inline-code">/v1/forms/:id</code> as form-urlencoded or JSON. List: <code class="inline-code">GET /v1/forms/:id</code>. Hidden <code class="inline-code">_redirect</code> sends browsers to thank-you page; honeypot <code class="inline-code">_gotcha</code> must stay empty.</p>
<p>Spam submissions return success without storage — do not use HTTP status alone to show user-facing errors for suspected spam. Legitimate users who trip false positives are rare if honeypot is positioned correctly — see troubleshooting in <a href="/guides/honeypot-spam-form">honeypot guide</a>.</p>
`,
  Catch: `
<h2>Catch as webhook plotting sheet</h2>
<p>Webhooks are asynchronous facts from third parties — Stripe, GitHub, Polar, custom partners. You cannot unit-test them with fixtures alone forever; you need real payloads. Plinth <a href="/catch">Catch</a> records those facts before your handler exists or while your laptop is offline.</p>
<p>Every Catch workflow in this category follows the same rhumb line: create bin (<a href="/docs/catch">docs</a>), register URL with provider, trigger event, inspect via <code class="inline-code">GET …/events</code>, implement handler, optionally <a href="/guides/webhook-replay">replay</a> on Pro. Signature verification guides (<a href="/guides/stripe-webhook-signature-test">Stripe</a>, GitHub HMAC in <a href="/guides/test-github-webhooks">GitHub guide</a>) sit between inspect and replay.</p>
<p>Compare ephemeral inspectors in <a href="/guides/webhook-site-alternative-free">Webhook.site alternative</a>. Understand retention in <a href="/guides/catch-bin-expire">Catch bin expiry</a> — bins are debug instruments, not durable queues. Export JSON fixtures before expiry for CI.</p>
<p>Catch shares billing with <a href="/forms">Forms</a> and <a href="/schema">Schema</a> on <a href="/pricing">Pricing</a>. MCP clients create bins via <a href="/docs/mcp">MCP</a>. When integration stabilizes, point production webhooks at your own endpoint and retire debug bins.</p>
<p>Security: bin URLs are unlisted, not authenticated. Do not expose bins in public repos or client-side code. Payloads may contain PII — handle exports accordingly.</p>
<h2>Catch API quick reference</h2>
<p>Create: <code class="inline-code">POST /v1/catch/bins</code>. Receive: any HTTP method to <code class="inline-code">/v1/catch/:binId</code>. List: <code class="inline-code">GET /v1/catch/:binId/events</code>. Replay: <code class="inline-code">POST /v1/catch/:binId/replay/:eventId</code> with body <code class="inline-code">{"url":"…"}</code> on Pro. Authorization headers redacted at capture — design handlers to tolerate missing auth on replay when testing signature paths separately.</p>
<p>Pair Catch with provider dashboards — Stripe and GitHub both show delivery status independent of Plinth. Use both views during integration: provider for whether they sent, Catch for what exactly they sent.</p>
`,
  Schema: `
<h2>Schema in the LLM pipeline</h2>
<p>Syntax and semantics split cleanly in production AI systems. Syntax — valid JSON text — is repaired by Plinth <a href="/schema">Schema</a> and <code class="inline-code">@plinth/schema</code>. Semantics — required fields, types, enums — are enforced by JSON Schema validation after repair. Constrained decoding from OpenAI or other providers reduces syntax errors but never replaces validation.</p>
<p>Guides in this category map to specific failure modes: <a href="/guides/llm-markdown-json-fence">markdown fences</a>, <a href="/guides/trailing-comma-json-fix">trailing commas</a>, <a href="/guides/python-true-in-json">Python booleans</a>. The overview <a href="/guides/llm-json-repair">LLM JSON repair</a> ties them together. <a href="/guides/structured-output-json-schema">Structured output JSON Schema</a> and <a href="/guides/json-schema-validate-openai">OpenAI validation</a> cover the validate-and-retry loop.</p>
<p>Call repair immediately after model output and before <code class="inline-code">JSON.parse</code>. Log <code class="inline-code">repairs</code> arrays to detect prompt or model regressions. Agents use MCP tools from <a href="/guides/mcp-json-repair">MCP JSON repair</a> at <code class="inline-code">https://api.plinthrun.com/mcp</code> (<a href="/docs/mcp">docs</a>).</p>
<p>HTTP endpoints mirror library behavior — <a href="/docs/schema">Schema docs</a>. Rate limits apply anonymously; attach API keys via <a href="/guides/polar-billing-api-keys">Polar billing</a> for production volume on <a href="/pricing">Pricing</a>.</p>
<p>Testing: keep fixture files of historically bad model outputs in CI. Repair and validate should pass on every main-branch commit.</p>
<h2>Schema API quick reference</h2>
<p><code class="inline-code">POST /v1/schema/repair</code> accepts raw text. <code class="inline-code">POST /v1/schema/validate</code> accepts parsed JSON plus schema. <code class="inline-code">POST /v1/schema/repair-and-validate</code> combines both — preferred for agent pipelines. Library methods mirror HTTP — import from <code class="inline-code">@plinth/schema</code> in Workers, Node, or Bun without network hop when latency matters.</p>
<p>When schema validation fails, return errors to the model as structured feedback rather than free-text summaries — models correct faster with JSON Pointer paths. Cap retries at one or two to control cost; persistent failure should route to human review queue.</p>
`,
  Platform: `
<h2>Platform bearings</h2>
<p>Plinth is open-core infrastructure on Cloudflare Workers, billed through Polar. Platform guides explain how pieces connect: hosted API at <code class="inline-code">api.plinthrun.com</code>, npm packages for self-hosters, and entitlements via <a href="/guides/polar-billing-api-keys">API keys</a> after checkout on <a href="/pricing">Pricing</a>.</p>
<p><a href="/guides/open-core-form-backend">Open-core form backend</a> documents @plinth/forms on Workers + D1. Product pages <a href="/forms">Forms</a>, <a href="/catch">Catch</a>, and <a href="/schema">Schema</a> each link to focused guides and <a href="/docs">documentation</a>. Solo builders often start anonymous on free tiers, ship, then upgrade when retention, replay, or webhooks become blockers.</p>
<p>Claim keys at /start after Polar webhook confirms payment. Keys look like <code class="inline-code">pln_live_…</code> — server-side only. Never embed in static HTML or client bundles.</p>
<p>When evaluating build vs buy, weigh engineer time operating D1, spam tuning, and webhook replay against hosted Plinth. Open core exists so you are never locked out of your own heuristics — not so every team must self-host.</p>
<p>Cross-links: contact forms (<a href="/guides/static-site-contact-form">static site</a>), webhook debug (<a href="/guides/test-stripe-webhooks">Stripe</a>), JSON repair (<a href="/guides/llm-json-repair">LLM repair</a>). The <a href="/guides">guides index</a> lists all 24 plot sheets.</p>
<h2>Reading order for new builders</h2>
<p>Start at <a href="/forms">Forms</a> if you need a contact page today. Add <a href="/catch">Catch</a> when integrating billing or GitHub automation. Add <a href="/schema">Schema</a> when LLM output feeds your database. Upgrade on <a href="/pricing">Pricing</a> when free retention or replay blocks shipping — not before you have working integrations.</p>
<p>Documentation hub: <a href="/docs">/docs</a>. Compare pages on the marketing site pit Plinth against Formspree, Webhook.site, and JSON repair alternatives. Open-core packages on npm mean you can inspect heuristics before trusting them — transparency is part of the product.</p>
`,
};
