name = "plinth-email"
main = "src/email.ts"
compatibility_date = "2026-09-01"

[vars]
PUBLIC_WEB_URL = "https://plinthrun.com"

[[d1_databases]]
binding = "DB"
database_name = "plinth"
database_id = "e82e85e2-ad15-42d2-8269-d9848c13cf63"
